### ISSUE TITLE
Warning in PaperMC 199 MC 1.14.4 No API version specified

### ISSUE THREAD

**Issue by Possemaster** [Minecrell/ServerListPlus#261]
Please fix the below warning, Plugin works fine, just a QOL fix i guess;

[WARNING] .... Plugin ServerListPlus v3.4.8 does not specify an api-version.

**Comment by Andre601** [comment]
This isn't really an issue.
Only a notification that SLP didn't set a version in its plugin.yml to inform Spigot if it supports 1.13 and newer, which it does.
You can just ignore this.

**Comment by Minecrell** [comment]
This is already fixed in the latest development builds. I just need to finish them up and release a new version.

**Comment by ping-localhost** [comment]
Did this ever get into the development builds, as it seems to be still happening:

```
22.04 20:58:44 [Server] ERROR [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
22.04 20:58:51 [Server] WARN Legacy plugin ServerListPlus v3.4.8 does not specify an api-version.
```

**Comment by stephan-gh** [comment]
> Did this ever get into the development builds, as it seems to be still happening:

@ping-localhost Yes, but 3.4.8 is the latest release and not the development builds :)
